### ISSUE TITLE
created pathname not optimal

### ISSUE THREAD

**Issue by daringer** [wor/goanysync#7]
While trying to compile a kernel inside a goanysynced directory I encounter the following problem:

Makefile:118: **\* multiple target patterns.  Stop.

This happens because there is a ":" inside the path generated by goanysync - Obviously one could write better Makefiles, but maybe goanysync should create better directory names to avoid such problems...

**Comment by wor** [comment]
Thanks. Yes, it's better to make the pathname simpler conserning the used characters.
